[Settings]
; The game resolution. Make it match with your in game dimensions BEFORE starting the game.
GameWidth = 1600
GameHeight = 900

; The key used to toggle the visibility of the hit and hurtboxes.
ToggleDisplayKey = 0x22

; The key used to increase opacity of the hit and hurtboxes.
ToggleOpacityAdd = 0x6B

; The key used to decrease opacity of the hit and hurtboxes.
ToggleOpacitySub = 0x6D