[Settings]
; The key used to toggle the visibility of the hit and hurtboxes.
ToggleDisplayKey = 0x22

; The key used to increase opacity of the hurtboxes.
ToggleOpacityAddHurtbox = 0x6B

; The key used to decrease opacity of the hurtboxes.
ToggleOpacitySubHurtbox = 0x6D

; The key used to increase opacity of the hitboxes.
ToggleOpacityAddHitbox = 0x6A

; The key used to decrease opacity of the hitboxes.
ToggleOpacitySubHitbox = 0x6F