[Settings]
; The game resolution. Make it match with your in game dimensions BEFORE starting the game.
GameWidth = 1600
GameHeight = 900

; The key used to toggle the visibility of the hit and hurtboxes.
ToggleDisplayKey = 0x22
